name: Build and Deploy NIFTY50 Dashboard

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python deps and fetch data
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r scripts/requirements.txt
          python scripts/fetch_data.py frontend/public/data/snapshot.json

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install and build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
